# Generated by Django 5.2.4 on 2025-07-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featrue',
            field=models.CharField(default='nothing', max_length=250),
            preserve_default=False,
        ),
    ]
