# Generated by Django 5.2.4 on 2025-07-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_featrue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featrue',
            new_name='feature',
        ),
    ]
