# Generated by Django 4.2 on 2025-07-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
