# Generated by Django 5.2.4 on 2025-07-21 08:16

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_product_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=order.models.generate_order_id, max_length=8, unique=True),
        ),
    ]
